# Book settings
title: Example PRObs system
author: UK FIRES
logo: logo.png

latex:
  latex_documents:
    targetname: book.tex

sphinx:
  extra_extensions:
    - sphinx_probs_rdf
  config:
    probs_rdf_system_prefix: "http://ukfires.org/probs/system/"
